export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const  CURRENT_RESTAURANT = 'CURRENT_RESTAURANT';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const FETCH_PICTURES = 'FETCH_PICTURES';
export const  CURRENT_PICTURES = 'CURRENT_PICTURES';